---
__netbox_deploy_api_url: "http://localhost:{{ netbox_deploy_port }}/api"
__netbox_deploy_healthcheck_url: "http://localhost:{{ netbox_deploy_port }}/login/"
__netbox_deploy_healthcheck_retries: 30
__netbox_deploy_healthcheck_delay: 10
